tigerProxy:
  adminPort: 8080
  proxyPort: 443
  tls:
    domainName: tiger-proxy
    serverRootCa: "/app/config/root.p12;changeit"
    #ocspSignerIdentity: "myOcspSigner.p12;Password"
  proxyRoutes:
    - from: /information
      to: http://information-service:8080/information
    - from: /
      to: http://vau-proxy-server:8080/
  activateRbelParsingFor:
    - epa3-vau
