server:
  port: 443
tigerProxy:
  adminPort: 8080
  proxyPort: 443
  tls:
    domainName: tiger-proxy
    serverRootCa: "/app/config/ca.p12;changeit"
    #ocspSignerIdentity: "myOcspSigner.p12;Password"
  proxyRoutes:
    - from: /
      to: http://vau-proxy-server:8080/
  activateEpa3VauAnalysis: true
