server:
  port: 8080
vau-proxy-server:
  direct-redirects:
    # information-service
    '[/information/api/v1]' : /information/api/v1
    '[/information/api/v1/ehr]': /information/api/v1/ehr
    '[/information/api/v1/ehr/consentdecisions]': /information/api/v1/ehr/consentdecisions
  cid-redirects:
    #authorization-service
    - /epa/authz/v1/getNonce
    - /epa/authz/v1/send_authorization_request_sc
    - /epa/authz/v1/send_authcode_sc
    # medication-service
    - /epa/medication/api/v1/fhir/*
    # medication-render-service
    - /epa/medication/render/v1/eml/xhtml
    - /epa/medication/render/v1/eml/pdf
    # entitlement-service
    - /epa/basic/api/v1/ps/entitlements
