zion:
  serverPort: 8080
  mockResponses:
    getConsentDecisionInformation:
      # add importance to choose this response, because getConsentDecisionInformation AND getRecordStatus matches
      importance: +1
      request:
        method: 'GET'
        path: '/information/api/v1/ehr/consentdecisions'
      assignments:
        insurantId: "$.header.x-insurantid"
      nested-responses:
        200permitPermit:
          response:
            statusCode: 200
            body: '[{ "functionId": "medication", "decision": "permit" }, { "functionId": "erp-submission", "decision": "permit" }]'
        200permitDeny:
          importance: +1
          request-criterions:
            # for medication testsuite (emilia)
            - "'${insurantId}' == 'X110421334'"
          response:
            statusCode: 200
            body: '[{ "functionId": "medication", "decision": "deny" }, { "functionId": "erp-submission", "decision": "permit" }]'
        200denyDeny:
          importance: +1
          request-criterions:
            # for medication testsuite (emilia)
            - "'${insurantId}' == 'X110426931'"
          response:
            statusCode: 200
            body: '[{ "functionId": "medication", "decision": "deny" }, { "functionId": "erp-submission", "decision": "deny" }]'
        400:
          importance: +1
          request-criterions:
            # if not set value is like search string
            - "'${insurantId}' == '$.header.x-insurantid'"
          response:
            statusCode: 400
            body: '{ "errorCode": "malformedRequest" }'
        404:
          importance: +1
          request-criterions:
            - "'${insurantId}' == 'X000000404'"
          response:
            statusCode: 404
            body: '{ "errorCode": "noHealthRecord" }'
        409:
          importance: +1
          request-criterions:
            - "'${insurantId}' == 'X000000409'"
          response:
            statusCode: 409
            body: '{ "errorCode": "statusMismatch" }'

    getRecordStatus:
      request:
        method: 'GET'
        path: '/information/api/v1/ehr'
      assignments:
        insurantId: "$.header.x-insurantid"
      nested-responses:
        204:
          response:
            statusCode: 204
        400:
          importance: +1
          request-criterions:
            # if not set value is like search string
            - "'${insurantId}' == '$.header.x-insurantid'"
          response:
            statusCode: 400
            body: '{ "errorCode": "malformedRequest" }'
        404:
          importance: +1
          request-criterions:
            - "'${insurantId}' == 'X000000404'"
          response:
            statusCode: 404
            body: '{ "errorCode": "noHealthRecord" }'
        409:
          importance: +1
          request-criterions:
            - "'${insurantId}' == 'X000000409'"
          response:
            statusCode: 409
            body: '{ "errorCode": "statusMismatch" }'

    setUserExperienceResult:
      request:
        method: 'POST'
        path: '/information/api/v1/userexperience'
      assignments:
        useragent: "$.header.x-useragent"
      nested-responses:
        201:
          response:
            statusCode: 201
        409: # parameter useragent is mandatory
          importance: +1
          request-criterions:
            # if not set value is like search string
            - "'${useragent}' == '$.header.x-useragent'"
          response:
            statusCode: 409
            body: '{ "errorCode": "requestMismatch", "errorDetail": "Header x-useragent is missing" }'
